#!/usr/bin/env python3
"""
Generates db/seed/seed.sql: deterministic seed data for hotel_bookings
and booking_events.

Deterministic (fixed random seed) so the seed file is reproducible and
diffable in version control, rather than regenerated with different
data on every run.

Usage:
    python3 generate_seed.py > seed.sql
    (or just run it - it writes seed.sql next to itself by default)
"""
import random
import uuid
from datetime import datetime, timedelta, timezone

random.seed(42)

CITIES = ["delhi", "mumbai", "bangalore", "hyderabad", "pune", "chennai"]
STATUSES = ["confirmed", "cancelled", "completed", "pending", "refunded"]
EVENT_TYPES = ["created", "payment_captured", "checked_in", "checked_out", "cancelled"]

NUM_ORGS = 8
NUM_BOOKINGS = 140  # comfortably over the required 100

ORG_IDS = [str(uuid.uuid4()) for _ in range(NUM_ORGS)]

NOW = datetime.now(timezone.utc).replace(microsecond=0)


def random_recent_datetime(days_back: int) -> datetime:
    """Random timestamp within the last `days_back` days, biased so a
    meaningful chunk of rows fall inside the last 30 days (needed for
    the target query to return non-trivial results)."""
    delta_days = random.uniform(0, days_back)
    return NOW - timedelta(days=delta_days)


def esc(value: str) -> str:
    return value.replace("'", "''")


def main():
    lines = []
    lines.append("-- seed.sql (generated by generate_seed.py, seed=42 - do not hand edit)")
    lines.append("BEGIN;")
    lines.append("")

    booking_rows = []
    booking_ids = []

    for i in range(NUM_BOOKINGS):
        booking_id = str(uuid.uuid4())
        booking_ids.append(booking_id)

        org_id = random.choice(ORG_IDS)
        city = random.choice(CITIES)
        status = random.choice(STATUSES)

        # ~65% of rows land within the last 30 days so the target
        # query (created_at >= now() - interval '30 days') has
        # realistic, non-empty results to group over.
        if random.random() < 0.65:
            created_at = random_recent_datetime(30)
        else:
            created_at = random_recent_datetime(365)

        checkin = created_at + timedelta(days=random.randint(1, 30))
        checkout = checkin + timedelta(days=random.randint(1, 7))
        amount = round(random.uniform(1500, 45000), 2)

        booking_rows.append(
            "({id}, {org}, {hotel}, {city}, {checkin}, {checkout}, {amount}, {status}, {created})".format(
                id=f"'{booking_id}'",
                org=f"'{org_id}'",
                hotel=f"'hotel-{random.randint(1, 40):03d}'",
                city=f"'{esc(city)}'",
                checkin=f"'{checkin.date()}'",
                checkout=f"'{checkout.date()}'",
                amount=amount,
                status=f"'{esc(status)}'",
                created=f"'{created_at.isoformat(sep=' ')}'",
            )
        )

    lines.append(
        "INSERT INTO hotel_bookings "
        "(id, org_id, hotel_id, city, checkin_date, checkout_date, amount, status, created_at) VALUES"
    )
    lines.append(",\n".join(booking_rows) + ";")
    lines.append("")

    # booking_events for roughly 60% of bookings, 1-3 events each
    event_rows = []
    for booking_id in booking_ids:
        if random.random() < 0.6:
            for _ in range(random.randint(1, 3)):
                event_type = random.choice(EVENT_TYPES)
                created_at = random_recent_datetime(30)
                payload = '{"source": "seed"}'
                event_rows.append(
                    "({booking}, {etype}, {payload}::jsonb, {created})".format(
                        booking=f"'{booking_id}'",
                        etype=f"'{esc(event_type)}'",
                        payload=f"'{payload}'",
                        created=f"'{created_at.isoformat(sep=' ')}'",
                    )
                )

    if event_rows:
        lines.append("INSERT INTO booking_events (booking_id, event_type, payload, created_at) VALUES")
        lines.append(",\n".join(event_rows) + ";")
        lines.append("")

    lines.append("COMMIT;")
    lines.append("")

    out_path = "seed.sql"
    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote {NUM_BOOKINGS} bookings and {len(event_rows)} events to {out_path}")


if __name__ == "__main__":
    main()
